AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template To Create Covid-19 ETL Pipeline.
Parameters:
  HashKeyElementName:
    Type: String
    Default: date
    Description: Hash Key Name
  HashKeyElementType:
    Type: String
    Default: S
    Description: Hash Key Type
  SubscriptionEndPoint:
    Type: String
    Description: Endpoint that will receive notifications from this SNS Topic.
  SubscriptionProtocol:
    Type: String
    Description: Protocol to use for notification.
    AllowedValues:
      - http
      - https
      - email
      - email-json
      - sms
      - sqs
    Default: email
Resources:
  ETLNotify:
    Type: AWS::SNS::Topic
    Properties: {}
  ETLNotifySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SubscriptionEndPoint
      Protocol: !Ref SubscriptionProtocol
      TopicArn: !Ref ETLNotify
  CovidTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: daily_covid
      AttributeDefinitions:
        -
          AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        -
          AttributeName: !Ref HashKeyElementName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DynSNSAccessforLambda
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
  LoadData:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        #Assumes s3 bucket named etldailycovidfunction with a zip file of load_data_and_notify.py
        S3Bucket: etldailycovidfunction
        S3Key: load_data_and_notify.py.zip
      Handler: load_data_and_notify.lambda_handler
      #Assumes the existence of a lambda layer containing 
      #pandas and the extract.py file created in AWS.
      Layers: 
        - arn:aws:lambda:us-east-1:898970573875:layer:better:1
      FunctionName: load_covid_data
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          dbtab : !Ref CovidTable
          jhurl : https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv
          nyurl : https://raw.githubusercontent.com/nytimes/covid-19-data/master/us.csv
          topic : !Ref ETLNotify
      Runtime: python3.7
      Timeout: 500
  ETLStart:
    Type: AWS::Events::Rule
    Properties:
      State: ENABLED
      ScheduleExpression: cron(0 17 * * ? 2021)
      Targets:
        - 
          Arn:  !GetAtt LoadData.Arn
          Id: StartPointNoon
Outputs:
  CovidETL:
    Description: daily_covid created using this template
    Value: !Ref CovidTable